version: '3.5'

services:
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - default
      - wow

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.server
    ports:
      - "8099:8099"
    env_file:
      - .env
    networks:
      - default
      - wow

networks:
  wow: