FROM golang:alpine as sources

WORKDIR /src

COPY go.* ./
RUN  go mod download

COPY . ./

RUN GOOS=linux GOARCH=amd64 GO111MODULE=on CGO_ENABLED=0 \
    go build -o server ./cmd/server/main.go

FROM alpine:latest

COPY --from=sources /src/server /opt/app/

USER 1000
WORKDIR /opt/app

CMD ["/opt/app/server"]